# Generated by Django 4.2.2 on 2023-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggerapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="categories",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
