# Generated by Django 4.2.2 on 2023-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggerapp", "0006_post_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="created_at",
            new_name="date_posted",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
